# Generated by Django 4.2.16 on 2024-10-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.PositiveIntegerField()),
                ("ticket_org_id", models.PositiveIntegerField()),
                ("validity_start", models.DateTimeField()),
                ("validity_end", models.DateTimeField()),
                ("barcode_data", models.BinaryField()),
                ("decoded_data", models.JSONField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.ticket"
                    ),
                ),
            ],
            options={
                "unique_together": {("ticket_number", "ticket_org_id")},
            },
        ),
    ]
