# Generated by Django 4.2.16 on 2024-10-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("deutschlandticket", "Deutschlandticket"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=255,
                verbose_name="Ticket type",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.CharField(
                max_length=32, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ticketinstance",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="main.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticketinstance",
            name="ticket_number",
            field=models.PositiveIntegerField(verbose_name="Ticket number"),
        ),
        migrations.AlterField(
            model_name="ticketinstance",
            name="ticket_org_id",
            field=models.PositiveIntegerField(verbose_name="Organization ID"),
        ),
    ]
