# Generated by Django 4.2.16 on 2024-10-07 22:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_ticket_ticket_type_alter_ticket_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketinstance",
            options={"ordering": ["-validity_start"]},
        ),
        migrations.AddField(
            model_name="ticket",
            name="pkpass_authentication_token",
            field=models.CharField(
                default=main.models.make_pass_token,
                max_length=255,
                verbose_name="Pass authentication token",
            ),
        ),
    ]
