# Generated by Django 5.0.9 on 2024-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ticket_last_updated_appleregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uicticketinstance',
            options={'ordering': ['-issuing_time'], 'verbose_name': 'UIC ticket'},
        ),
        migrations.AlterModelOptions(
            name='vdvticketinstance',
            options={'ordering': ['-validity_start'], 'verbose_name': 'VDV ticket'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('deutschlandticket', 'Deutschlandticket'), ('bahncard', 'Bahncard'), ('fahrkarte', 'Fahrkarte'), ('reservierung', 'Reservierung'), ('interrail', 'Interrail'), ('unknown', 'Unknown')], default='unknown', max_length=255, verbose_name='Ticket type'),
        ),
    ]
