# Generated by Django 5.0.9 on 2024-10-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='db_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
