# Generated by Django 5.0.9 on 2024-10-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_account_db_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='db_cookies',
            field=models.JSONField(blank=True, null=True, verbose_name='Deutsche Bahn Cookies'),
        ),
        migrations.AlterField(
            model_name='account',
            name='db_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Deutsche Bahn Account ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='db_token',
            field=models.TextField(blank=True, null=True, verbose_name='Deutsche Bahn Bearer token'),
        ),
    ]
