# Generated by Django 5.0.9 on 2024-10-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_account_db_cookies_alter_account_db_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='db_cookies',
        ),
        migrations.AddField(
            model_name='account',
            name='db_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Deutsche Bahn refresh token'),
        ),
        migrations.AddField(
            model_name='account',
            name='db_refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deutsche Bahn refresh token expiration'),
        ),
        migrations.AddField(
            model_name='account',
            name='db_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deutsche Bahn Bearer token expiration'),
        ),
    ]
