# Generated by Django 5.0.9 on 2024-10-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_account_db_cookies_account_db_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saarvv_token',
            field=models.TextField(blank=True, null=True, verbose_name='SaarVV Token'),
        ),
    ]
