# Generated by Django 5.0.9 on 2024-10-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_account_saarvv_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saarvv_device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SaarVV Device ID'),
        ),
    ]
