# Generated by Django 5.0.9 on 2024-10-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_account_saarvv_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main.account'),
        ),
    ]
