# Generated by Django 5.0.9 on 2024-10-12 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_dbsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsubscription',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.account'),
            preserve_default=False,
        ),
    ]
