# Generated by Django 5.0.9 on 2024-10-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_dbsubscription_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbsubscription',
            options={'verbose_name': 'DB Subscription', 'verbose_name_plural': 'DB Subscriptions'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='db_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main.dbsubscription'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
