# Generated by Django 5.0.9 on 2024-10-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_uicticketinstance_validity_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='saarvv_acccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saarvv_tickets', to='main.account'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='db_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main.dbsubscription', verbose_name='DB Subscription'),
        ),
    ]
